spring:
  profiles:
    active: prod

kudu:
  url: vm172-18-6-7:7051,vm172-18-6-13:7051,vm172-18-6-16:7051
#impala cluster info
impala:
  url: jdbc:impala://${impala_ip}:21050/default;AuthMech=3;UID=${uid};PWD=${pwd};
  driver: com.cloudera.impala.jdbc41.Driver